### ISSUE TITLE
Increase the reward of skinning to match other professions.

### ISSUE THREAD

**Issue by Sharinkyo** [gamefreedomgit/Deathwing#14]
**Description:**

I don’t know the exact rates of skinning but it’s VERY low compared to mining, fishing and herbalism…

Mobs from Tol Barad and Twilight Highlands usually reward the skinner with 4-6 pieces of leather without any rates. I receive about 9-14 with the rates so I assume it is around 2x (compared to fishing which is 5x? That’s what I read in the change log)

This isn’t my biggest issue with skinning though because on very rare occasions I receive the “strange bloated stomach” but it only contains 1-2 volatiles… and the drop rate is standard (1%)… I received 7 so far and I’ve skinned way past 1.000 mobs now… (I’ve received more world epics than strange bloated stomachs…)

Leatherworkers need a ton of volatiles but don’t really have a way of farming them through skinning so please increase the drop rates of stranger bloated stomach or increase the amount it gives upon opening.

That’s it! 😁
Thanks for hosting an awesome cataclysm server! 🔥

**How to reproduce:**

Grab yourself a skinning knife and start grinding the spiders in Tol Barad, you can also have some fun with the rogue bots while at it.

**How it should work:**

It works as intended but the rates are very low compared to herbalism, mining and fishing.

**Database links:**
Strange bloated stomach: 
https://www.wowhead.com/item=67495/strange-bloated-stomach

**Comment by Sharinkyo** [comment]
I was told by head game master Isa to report it here.

**Comment by UltraNix** [comment]
Skinning loot is already increased by the same multiplier as herbalism or mining.
E.g.https://www.wowhead.com/npc=46508/darkwood-lurker - normally gives 1-3 leather, now it's 5 - 15.

**Comment by Sharinkyo** [comment]
Thanks for replying to my bug UltraNix and I’m Happy you have already made changes to the Strange bloated stomach, may I ask much how it was increased?

That said I fail to see how the spider normally gives 1-3 pieces of leather when the link states that it gives 1-7 pieces of leather? It’s a shame that wowhead.com/cata does not have the skinning rewards on the mob.

thank you for the anwser and quick solution on strange bloated stomachs!

**Comment by UltraNix** [comment]
Yeah - it's already updated to retail.
That 1-3 it's our DB.

**Comment by UltraNix** [comment]
Fixed.
