### ISSUE TITLE
Fishing schools not affected by increased rates

### ISSUE THREAD

**Issue by Sharinkyo** [gamefreedomgit/Deathwing#16]
**Description:**
I started leveling my cooking and fishing earlier today and while fishing in Eastern Plaguelands I noticed the “Greater Sagefish Schools”. This made me remember the guild achievement to catch 10.000 fish from fishing pools.

I then started grabbing all schools I could see but quickly noticed that I only received 1 fish each time.

is this intentional or a bug?

**How to reproduce:**

Grab a fishing pole and start fishing! 😅

**How it should work:**

I believe they should be affected by the increased rates.

**Database links:**

**Comment by AlucardHellsingChapel** [comment]
ye i hope it gets fixed

**Comment by UltraNix** [comment]
Fixed.
