### ISSUE TITLE
OS25 NO ACHIEVE + Mount for Server First

### ISSUE THREAD

**Issue by Stormqt** [gamefreedomgit/Deathwing#2]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

![image](https://github.com/gamefreedomgit/Deathwing/assets/166875206/197cb71d-987b-4cd1-9716-258f05f14638)

**Description:**
3  drakes OS25 server first, no mount dropped or achieve, or title.

**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by GM-Nightmaree** [comment]
#3 Duplicate
