### ISSUE TITLE
Hellfire peninsula chain quest bugged

### ISSUE THREAD

**Issue by Wolfurion** [gamefreedomgit/Deathwing#20]
did all the 14 quests to get "Overlord" and doesnt give me the quest
https://www.wowhead.com/cata)](https://www.wowhead.com/quest=10400/overlord) there is the quest and the chain. 
It says need lvl 58 so there shoudnt be an issue, i also did the quest item, all did this too many times.

**Comment by PanJanuszek** [comment]
fixed 24.04.2024
