### ISSUE TITLE
Blackrock Caverns, 3rd boss, Karsh Steelbender Heroic

### ISSUE THREAD

**Issue by mettios** [gamefreedomgit/Deathwing#21]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Sometimes (usually after a wipe), number of stacks (Superheated Quicksilver Armor) he takes under the stream of molten metal (center of the room) does not match with amount of time he actually has been there. The stacks seem to rapidly increase from 4 to 8 or 20 in 1 second resulting in a wipe.

**How to reproduce:**
pull the boss first and wipe! do it again this time only let him pass through center of the room for 1 second, and watch the stacks he gains. If it's bugged, it will jump from 0 to 4. 

**How it should work:**
He should gain one stack per second while under the stream of molten metal.

**Database links:**
https://www.wowhead.com/cata/npc=39698/karsh-steelbender
[Superheated Quicksilver Armor](https://www.wowhead.com/cata/spell=75846/superheated-quicksilver-armor)

**Comment by UltraNix** [comment]
Fixed.
