### ISSUE TITLE
Druid tier shoulders not able to buy with token

### ISSUE THREAD

**Issue by nolloe** [gamefreedomgit/Deathwing#23]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**Boomkin tier shoulders require agility tier gloves and glove token to purchase 

**How to reproduce:**

**How it should work:**
Druid tier shoulders should require tier token just like feral and resto shoulders do 

**Database links:**

**Comment by GM-Nightmaree** [comment]
![image](https://github.com/gamefreedomgit/Deathwing/assets/157993777/5a8a4257-73e0-4a18-aa20-f53a77190248)
![image](https://github.com/gamefreedomgit/Deathwing/assets/157993777/dc82119e-e507-453c-92f1-bba7c521b36b)
![image](https://github.com/gamefreedomgit/Deathwing/assets/157993777/693ddb23-b295-46da-887c-7ab3932a46a1)
this is a screenshot of the items
_**ITS ONLY HORDE SIDE**_
npc **Jamus'Vaz**
Correct item requirement should be : 64314 (Mantle of the Forlorn Vanquisher)
