### ISSUE TITLE
He Who Would Be Forgiven quest broken NPC is missing

### ISSUE THREAD

**Issue by AbyssPL12** [gamefreedomgit/Deathwing#24]
**Description:**
The NPC is missing and you can't return the quest or take it from him if you abandoned it first. The NPC can't be also found with /target command.

**How it should work:**
After completing the quest prior A Trip to the Moonwell you should be able to go to Raynewood Tower and speak with Avrus Illwhisper to complete the quest.

**Database links:**
https://www.wowhead.com/quest=14018/he-who-would-be-forgiven#comments
https://www.wowhead.com/npc=34335/avrus-illwhisper
![WoWScrnShot_042024_210445](https://github.com/gamefreedomgit/Deathwing/assets/94023242/bcea982b-e376-455d-b8cb-72650c7ee40d)

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/2754

**Comment by PanJanuszek** [comment]
What client do you have ??

Mini ?? EN?? ES?? RU??
