### ISSUE TITLE
abalorio bug 

### ISSUE THREAD

**Issue by Humberto95159** [gamefreedomgit/Deathwing#25]
![wow 1](https://github.com/gamefreedomgit/Deathwing/assets/167715612/9ba99796-63e3-473d-ac77-d87ae845aa32)

https://www.wowhead.com/es/item=64645/mu%C3%B1eca-favorita-de-tyrande
it bug

**Comment by UltraNix** [comment]
Looks like corrupted game file.

**Comment by PanJanuszek** [comment]
Mini or full client?
