### ISSUE TITLE
Achievement [Kill It With Fire!] does not work

### ISSUE THREAD

**Issue by weiderrr** [gamefreedomgit/Deathwing#28]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The achievement requires you to drag 3 souls thru fire which kills them. The problem is the fire does nothing to these souls.

**How to reproduce:**
Position Harbinger of Darkness in a way that a soul has to go thru fire to reach him. See that even after 5 seconds of burning the only thing that happens is a refresh on burning debuff.
![WoWScrnShot_042224_204210](https://github.com/gamefreedomgit/Deathwing/assets/83502405/7c3a014e-d980-414f-9a6c-980c475e1a7b)
![WoWScrnShot_042224_204212](https://github.com/gamefreedomgit/Deathwing/assets/83502405/c42887bb-a86a-4b6e-beee-226506a8eb68)

**How it should work:**
The souls should die after staying in the fire for a second.

**Database links:**
https://www.wowhead.com/achievement=5290/kill-it-with-fire

**Comment by UltraNix** [comment]
The souls must touch the flames, then they transform into Burning Souls - then you can kill them. 
Flames should not do any damage.

**Comment by weiderrr** [comment]
My apologies that "How it should work:" part was not filled correctly. Earlier we also tried killing them in the fire but our tracker never moved from 0/3. Here is a screenshot right before a soul dies in the flames with the debuff.
![WoWScrnShot_042224_204156](https://github.com/gamefreedomgit/Deathwing/assets/83502405/8256c42f-295a-474b-adea-3fc300ee2d64)

**Comment by weiderrr** [comment]
@UltraNix were you able to complete the achiev or at least gain 1/3?

I'm pretty sure we tried killing them in the fire by ourselves as shown in the last screenshot, but if you somehow managed it. I'll spend a few more hours on it.

**Comment by weiderrr** [comment]
The achievement works indeed.
