### ISSUE TITLE
No loot table in Watertight Trunk

### ISSUE THREAD

**Issue by Allie2c** [gamefreedomgit/Deathwing#29]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
There's no loot inside it 
(Also it was fixed on maelstrom and apparently not here, probably should check out  
 - Worn Junkbox.
 - Sturdy Junkbox.
 - Heavy Junkbox.
 - Scum Covered Bag
  These were apparently fixed along with Watertight Trunk on maelstrom according to changelog-cata)

**How to reproduce:**
Just go open it and there's no loot, opened like 10 and haven't gotten any loot

**How it should work:**
It should have atleast 2-3 of any of the random items it should drop according to wowhead but once again it was fixed on maelstrom so it should be a fast one to fix.

**Database links:**
https://www.wowhead.com/classic/item=21113/watertight-trunk#contains

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/4a5e0531-5e6e-43f8-9c51-c55de2713c10)
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/2b64c4d3-2a9b-405f-9953-c3cabd616698)
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/4c222e4d-f64c-4218-9cb5-6b5c8de5984e)

cannot reproduce
