### ISSUE TITLE
Realmfirst 25 OS Title 

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Deathwing#3]
**Description:**
A group did OS 25 Man and didnt get mount or realm first achievement nor title
Screenshots :
https://cdn.discordapp.com/attachments/1228463580102529055/1228463674314719393/WoWScrnShot_041224_235226.jpg?ex=662c22f3&is=6619adf3&hm=1cf070f95c4083b211abc46269498c9e60c5252572c01e7d58aa688e6507c7da&

https://cdn.discordapp.com/attachments/1228463580102529055/1228463674725896273/WoWScrnShot_041224_234907.jpg?ex=662c22f3&is=6619adf3&hm=ea333ce24b2ef74f4b82e3e0c61e138d1f1a30a689a87636cf63155cd07ae81c&

https://cdn.discordapp.com/attachments/1228463580102529055/1228463675086737549/WoWScrnShot_041224_235032.jpg?ex=662c22f3&is=6619adf3&hm=56c207e60d92a5663a21878a727dd311f5b3efcf1e4c0a5dc2b1a43e09578776&

**How it should work:**
players should have The title Obsidian Slayer after realm first OS 25

**Database links:**
https://www.wowhead.com/achievement=456/realm-first-obsidian-slayer

**Comment by UltraNix** [comment]
It's disabled because this boss is not scripted properly.
