### ISSUE TITLE
Deathwing only: Shadowfang Keep Heroic drops 1x loot only

### ISSUE THREAD

**Issue by RubyOnWhitemane** [gamefreedomgit/Deathwing#31]
**Description:** All bosses in SFK HC only drop their regular 1x loot amount, it's not doubled like in all other dungeons.

https://imgur.com/a/d3Vp4PF

**How to reproduce:** Kill any boss in SFK HC.

**How it should work:** Loot should be doubled.

**Database links:** https://www.wowhead.com/zone=209/shadowfang-keep#npcs

**Comment by UltraNix** [comment]
Fixed.
