### ISSUE TITLE
Guild fishing achievement

### ISSUE THREAD

**Issue by Bakalogatos** [gamefreedomgit/Deathwing#37]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Individual Fishing achievements scale with the drop rate, if I catch 5 fish it increases by 5, if I catch 2 by 2 etc. But for the Guild achievement 'That's a Lot of Bait" everything counts as 1 fish.

**How to reproduce:**
Go fishing and check the achievement rate of increase

**How it should work:**
Guild achievement should also go up by as many fish as you catch

**Database links:**

**Comment by UltraNix** [comment]
Fixed.
