### ISSUE TITLE
Error in the blacksmithing profession regarding gloves

### ISSUE THREAD

**Issue by DonJuanatus** [gamefreedomgit/Deathwing#38]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Nombre de cuenta :Aspros 
Personaje: Manzanita
Servidor: Deathwing

Hello GM, I found a bug or error regarding the Blacksmithing profession. When you put a gem slot in the gloves with the Blacksmithing 400 profession, it does not recognize the color of the gem you are putting in and I checked this with the meta gem (Chaotic Shadowspirit Diamond) that is placed on the head and the benefit of the 3 red gems is not activated (it does appear but it is an apparent deception) because it does not increase the statistics such as the critical hit or the 3% critical effect, this only happens in the gloves more on the bracers if it works well or it recognizes the gem color and there is no problem with the target gem.

Besides, it deceives you with the white color of the benefit of the target gem, it appears to recognize but if you look at the statistics it does not go up or increase, the benefit remains or stagnates like before placing the target gem
**How to reproduce:**
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/ae603dbd-a388-4669-abd9-dacfdf5b08e7)
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/1fecd0ef-ce39-43f2-b24b-7811f0603462)
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/3952b278-0ba9-4de4-9d20-a0680b94635f)
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/5b587dd5-c3a8-45bf-bfd5-3c28a400bc24)

As you can see, he has 168 critical hit, which is the sum of only the gloves and the head minus the meta gem, when in reality he should have 222 critical hit if he had the meta gem benefit active, that does not happen with the bracers. because it works well, it recognizes the color of the gem
**How it should work:**
In the case of the bracers, there is no problem, the target gem recognizes the color of the red and orange gem and the benefit is activated and it does not deceive you with an appearance and the statistics, if added, are as they should be.
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/76841571-3b49-4676-a2b3-a756bf013f06)
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/58024cfd-e4d2-40c4-add2-44afd445355d)
![image](https://github.com/gamefreedomgit/Deathwing/assets/168039627/e0f6f251-218a-4b41-92f7-7e36d847c2c2)

**Database links:**

**Comment by UltraNix** [comment]
Without belt with prismatic gem:
![image](https://github.com/gamefreedomgit/Deathwing/assets/80540499/cc854960-7899-457b-b56a-dbc415bc997e)

With belt and prismatic gem in it:
![image](https://github.com/gamefreedomgit/Deathwing/assets/80540499/99998b83-8bf4-4f90-8d1c-bed04af64de5)

There is no bug here.
As you can see - critical strike rating is properly displayed in your UI.
The aura from meta (increased critical healing and damage bonus) is not displayed in your UI.

**Comment by DonJuanatus** [comment]
GM, the problem is not with the belt because it works well just like the blacksmithing bracers, but with the blacksmithing slot 400 gloves, they are the ones that do not detect the color of the target gem and therefore the target gem does not activate its benefits. his stats don't go up
