### ISSUE TITLE
Draenei Heroic Presence not working

### ISSUE THREAD

**Issue by tomqtx** [gamefreedomgit/Deathwing#39]
**Description:**
Heroic Presence (Draenei passive) does not grant 1% hit like it should

**How to reproduce:**
Play a caster, get 3% hit with items and 1% from passive and your skills will still miss even though 4% is cap (slight edit, this is for pvp)

**How it should work:**
Heroic presence should grant 1% spell hit and attack hit

**Database links:**
Just in the spellbook tooltip

**Comment by UltraNix** [comment]
Heroic Presence is already included in your UI spelhit stat.
That spell works okay.
