### ISSUE TITLE
No RHC rewards

### ISSUE THREAD

**Issue by Avalanchehp** [gamefreedomgit/Deathwing#4]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
It happened to me and my friends 3 times already, If you que in a party for RHC/normal dung, you don't get the bonus rewards at the end of the dungeon (for rhcs, its 350 valor points)

**How to reproduce:**
Que up in a party with somebody, finish the dungeon.

**How it should work:**
It should give bonus rewards to everybody that finished the dungeon

**Database links:**
https://www.wowhead.com/guide=cataclysm&pve

**Comment by UltraNix** [comment]
Justedt tested queueing up being in party - at the end of dungeon, everybody got Valor Points.
@Avalanchehp Are you sure you weren't capped?

**Comment by WhitemaneIsa** [comment]
@UltraNix this happens sometimes when the group replaces someone mid dungeon. It's quite impossible to get capped on Deathwing with 100k.

**Comment by UltraNix** [comment]
@WhitemaneIsa Should be okay now. Let me know once new problems with it arrives.
