### ISSUE TITLE
Halls of Stone bugged boss encounter

### ISSUE THREAD

**Issue by boom43** [gamefreedomgit/Deathwing#40]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:** Third boss encounter "Tribunal of the Ages" in Halls of Stone (lich king dungeon) is bugged and can't be done.
I tried dungeon 2 times, first time It let me talk to Brann once and he just ran all the way to instantly start fight, without talking him to start the fight (need to talk 2 times in total) fight was going good, but after it ended Brann just vanished and I did not get loot.
Next day I tried to do it again and could not talk to Brann at all.

**How to reproduce:** Talk to Brann Bronzebeard (third boss in dungeon).
He is also only available after beating first 2 bosses [Maiden of Grief] and [Krystallus]

**How it should work:** The Tribunal of the Ages encounter requires that you pick up [Brann Bronzebeard] by speaking to him at an open space in the corridor leading to [Tribunal of the Ages]. He will then accompany you to the encounter room where you will need to speak to him again to start the encounter.

**Database links:** https://www.wowhead.com/wotlk/guide/halls-of-stone-overview

**Comment by PanJanuszek** [comment]
fixed 26.04.2024, server restart required
