### ISSUE TITLE
The Twilight Overlook quest does not show up after previous quest completion

### ISSUE THREAD

**Issue by JaniceLu** [gamefreedomgit/Deathwing#41]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Completing quest, "Quicksilver Submersion", should start next quest in the Upper World Pillar Fragment questline. However, the questgiver does not have next quest available. This is preventing the continuation of the Deepholm quest chain. I have checked to make sure that commonly missed quests such as Captain's Log have been completed as well.

**How to reproduce:**
1. Complete quest, "Quicksilver Submersion" by turning in to Maruut Stonebinder. 
2. Observe that Maruut Stonebinder does not have a follow-up quest, which should be "The Twilight Overlook".

**How it should work:**
1. Complete quest, "Quicksilver Submersion" by turning in to Maruut Stonebinder.
2. Accept next quest that Maruut Stonebinder gives, which should be "The Twilight Overlook".

**Database links:**
https://www.wowhead.com/quest=27010/quicksilver-submersion
https://www.wowhead.com/quest=27061/the-twilight-overlook

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/e350371d-8312-4f77-a956-93230e26b8f3)
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/2859da1a-086d-4f26-aa44-32caa6f65cba)

So what's the problem??

Did all your steps.
Cannot reproduce
