### ISSUE TITLE
Quest bugged:  [Field Test: Gnomecorder]

### ISSUE THREAD

**Issue by Jenkinns** [gamefreedomgit/Deathwing#42]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
quest does not auto-complete when near the drill

**How to reproduce:**
accept quest
go to the drill location down the path - nothing happens

**How it should work:**
it should auto-complete and provide the next quest in the chain

**Database links:**
https://www.youtube.com/watch?v=LyNcZi402qY

**Comment by PanJanuszek** [comment]
fixed 26.04.2024, server restart required
