### ISSUE TITLE
Achievement "Thats alot of bait" not working with the new drops

### ISSUE THREAD

**Issue by Wolfurion** [gamefreedomgit/Deathwing#44]
Achievement **https://www.wowhead.com/achievement=5036/thats-a-lot-of-bait** is not working, you have to fish 10k fish from fishing pools, you get 2-6 every catch but only counts as one, by the time my guild has 2.5k+ but i already got alot more than the Ach requires

Is not counting how many fish you get, only counts one

by fishing in fishing pools and not counting them as they should

if you get 6 fish should count as 6 fish not 1
 
 
Btw the other ach from mining/disenchanting/skiinning/herb are working seems like the only one is not is this one, so please help

**Comment by UltraNix** [comment]
#37
