### ISSUE TITLE
fixed 26.04.2024, after restart

### ISSUE THREAD

**Issue by Lukbexer** [gamefreedomgit/Deathwing#46]
fixed 26.04.2024, after restart

_Originally posted by @PanJanuszek in https://github.com/gamefreedomgit/Maelstrom/issues/5922#issuecomment-2079315252_

Server Deathwing, quest "Put it on" in Abyssal Depths for Alliance.
https://www.youtube.com/watch?v=i_TPaBfktrg

**Comment by PanJanuszek** [comment]
Dunno what does it mean above.

Problem is solved, if not open it again

![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/e14b126f-ef6e-422c-a5b7-ecf9b807c85d)
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/c9ccd537-d8e8-4fff-9d6a-649f7c8044f8)
