### ISSUE TITLE
Alliance TBC Quest [Blast the Infernals!] cant be finished.

### ISSUE THREAD

**Issue by wickedlike** [gamefreedomgit/Deathwing#47]
**Description:**
When I take [Blast the Infernals!], and go finish it, I get the yellow in game text that i did the task required.
But when I open my quest log, it stays as unfinished and i cant turn it in to move to the other quests in the chain.

**How to reproduce:**
Take the alliance version of [Blast the infernals!] and do it

**How it should work:**
Should have the quest complated

**Database links:**
https://www.wowhead.com/cata/quest=10564/blast-the-infernals
https://www.youtube.com/watch?v=sPQFt0AjHFs&ab_channel=WCQuests

https://github.com/gamefreedomgit/Deathwing/assets/156576564/571c7eb9-7706-4ebf-b711-2ff91aa965e6

**Comment by wickedlike** [comment]
Reloging fixes this, but shows no indicator that it works. 
It still does not update the quest log, but atlest it lets me turn in the quest and move in. 
Feel free to close this.

**Comment by PanJanuszek** [comment]
Fixed 05.05.2024 serwer restart rewuired
