### ISSUE TITLE
Herb bag bugg

### ISSUE THREAD

**Issue by Khalthous** [gamefreedomgit/Deathwing#48]
![Screenshot 2024-04-28 014254](https://github.com/gamefreedomgit/Deathwing/assets/158604339/725a475a-9c39-43c8-a273-7f200b144ab1)

Hello, so I've bought a couple of herb bags for 1,500 JP each, opened the first one was completely empty, felt like i got scammed hard, but then opened the other one, and got less than 20* so a little less of a scam, then opened the 3rd one was fine.

Please let me know if I can be refunded in game or something for the lost of Empty bag, thank you.

Khalthus

**Comment by UltraNix** [comment]
Fixed.
