### ISSUE TITLE
Cant mine low lvl Elemental Mobs

### ISSUE THREAD

**Issue by Ieluy** [gamefreedomgit/Deathwing#49]
Hello
Most of elementals mobs cant be mined and doesnt have such option when mouse on.
Corrupted Cliff Gigant - Obsidium elemental and so on...
Cant farm deeprock salt. Btw it must to work anyway.
Thank You.

**Comment by UltraNix** [comment]
@Ieluy Every such mob must be updated separately, so please report them all here.

**Comment by Ieluy** [comment]
Please fix this 2 for the first time.

**Comment by UltraNix** [comment]
Fixed.
