### ISSUE TITLE
Bugs quest - 

### ISSUE THREAD

**Issue by Zadkiel124** [gamefreedomgit/Deathwing#51]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)
Hello, I have a problem with the quest for the Twilight Highlands chain.

**Description:**
NPC: https://skr.sh/sPTqGwHJyQc
Disappears when trying to approach him to complete the quest "combat vehicles"
Change location: https://skr.sh/sPTvsgxP0Nb
https://skr.sh/sPTm5WjrB3u
**How to reproduce:**

**How it should work:**

**Database links:**
https://www.wowhead.com/ru/quest=26293/боевые-машины
https://www.wowhead.com/ru/npc=42672/штейгер-глиббс

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/1c7fbf6e-e88d-44ab-a5b5-4c2454d70c7b)

cannot reproduce. Issue i think is related to spanish or russian clients. Mostly mini-clients
