### ISSUE TITLE
Watertight Trunk

### ISSUE THREAD

**Issue by Allie2c** [gamefreedomgit/Deathwing#53]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Not giving loot mostly 

**How to reproduce:**
Make sure to fish the trunk and try opening alot. Don't generate the item in your inventory
https://gyazo.com/7796e6e32ed1e5369285ba1c18991e97

**How it should work:**
https://www.youtube.com/watch?v=QMNpj3NmIss
At 5:20 he starts opening Watertight Trunks
It should have atleast some silvers and coppers and random items not just EMPTY loot
**Database links:**

https://www.wowhead.com/item=21113/watertight-trunk#comments

**Comment by PanJanuszek** [comment]
fixed 08.05.2024, after restart
