### ISSUE TITLE
Crucible of carnage arena chainquest

### ISSUE THREAD

**Issue by GM-Nightmaree** [gamefreedomgit/Deathwing#56]
**Description:**
Gurgthock doesnt reset after someone takes the quest 
it has to give you option to continue the chainquest after killing the first boss
27863 first quest (id) 
first quest isnt completing 
i have to .die .respawn npcs after each quest 
**How it should work:**
npc should reset after each quest (boss kill)
and killing the boss should give credit

**Database links:**
https://www.wowhead.com/quest=27863/the-crucible-of-carnage-the-bloodeye-bruiser
https://www.wowhead.com/npc=46935/gurgthock
https://www.wowhead.com/npc=46936/wodin-the-troll-servant

**Comment by PanJanuszek** [comment]
fixed 08.05.2024, restart required
