### ISSUE TITLE
Gravity Crush does too much damage on 25 heroic

### ISSUE THREAD

**Issue by dccdcd** [gamefreedomgit/Deathwing#57]
**Description:**
On phase 3 of Ascendant Council on 25 heroic the boss will lift 6 players each time it casts gravity crush and deal 9% of their maximum health per 0.5 secs. This version of the ability never existed in cataclysm as when the damage was increased to 9% in MoP prepatch they also decreased the number of affected players to 3. It should instead just deal 6% of the players maximum health per 0.5 secs in physical damage.

Also Blessing of Protection should stop damage from the ability, as it is physical damage, but you still take damage with BoP.

**How to reproduce:**
Get to the last phase of Ascendant Council 25 Heroic and watch as 6 people get lifted into the air and take more than 6% of their max health in damage per ability tick when gravity crush is cast. When you BoP a player they will continue to take damage from the ability.

**How it should work:**
Affected players should take 6% of their maximum health as physical damage per 0.5 secs during gravity crush. When they get Blessing of Protection they should stop taking damage from gravity crush.

**Database links:**
https://www.wowhead.com/spell=84948/gravity-crush#changelog

**Comment by UltraNix** [comment]
On normal version it's 6%, on heroic - 9%. It's from 4.3.4 spell files.
```
92487 Gravity Crush
Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 9
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 89 (SPELL_AURA_PERIODIC_DAMAGE_PERCENT), value = 9, misc = 0 (0), miscB = 0, periodic = 500
Max Radius (Id 12) 100,00
```

As for Blessing  of Protection: that spell has special attibute that obbey such effects.
```
ID - 84948 Gravity Crush
=================================================
Description: Traps an enemy in a gravity bubble, lifting them off the ground and crushing them for $s2% of their maximum health every $t2 sec for $d.  When the effect ends, the target will be left to fall to the ground.

ToolTip: Stunned.
Taking damage equal to $s2% of maximum health every $t2 sec.
Category = 1152, SpellIconID = 174, activeIconID = 0, SpellVisual = (17975,0)
Family SPELLFAMILY_GENERIC (0), flag [0] 0x00000000 [1] 0x00000000 [2] 0x00000000

SpellSchoolMask = 1 (SPELL_SCHOOL_MASK_NORMAL)
DamageClass = 0 (SPELL_DAMAGE_CLASS_NONE)
PreventionType = 0 (SPELL_PREVENTION_TYPE_NONE)
=================================================
Attributes: 0x20000000 (SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY)
AttributesEx1: 0x00000004 (SPELL_ATTR1_CHANNELED_1)
AttributesEx3: 0x00000100 (SPELL_ATTR3_ONLY_TARGET_PLAYERS)
=================================================
SpellLevel = 0, BaseLevel = 0, MaxLevel =  0, MaxTargetLevel = 0, ConeAngle = 0
```
`SPELL_ATTR0_UNAFFECTED_BY_INVULNERABILITY`
