### ISSUE TITLE
Desolace - Deep Impact Quest Bug

### ISSUE THREAD

**Issue by Anderrite** [gamefreedomgit/Deathwing#59]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Character: Lvl 36 Worgen Rouge
Quest: Deep Impact, Desolace
When interacting with the "rubble" using the assigned skill in the Naga Disguise the game spawns the tablets the player supposed to interact with. Theoretically the player needs to destroy a couple of these rubbles using the skill and collecting the tablets until the game gives you the right one. Then combine 4 of these to complete the quest item they need to submit.

When I first interacted with a rubble and interacted with the tablet, it gave me the required one straight away, however the loot window contained a stack of 6  tablets instead of one. The game then displayed an error message along the lines of " You cannot take any more of these items" and didn't allow me to loot any of them. And to answer the obvious question, yes I had plenty of inventory space.

I've tried relogging and re-launching the game as well as abandoning and accepting the quest again to no avail. I have not tried it with multiple characters.

**How to reproduce:**

Accessing the quest:
Progress in the Desolace quest chain until you reach the "Slitherblade Slaughter" part of the chain. The Druid will ask you to interact with a naga called Valishj who will give you two quests, the second of which is Deep Impact. 

The bug:
Swim to the designated area and look for an "Ancient Rubble" on the seafloor. Swim close and use the Shatter Rubble ability on the taskbar, then click on the small stone tablets that spawn. Most of them will yield nothing when interacted with (probably another bug, as the retail version gives you some vendor items), however eventually one of them should give you  a stack of six  quest items called "Ancient Tablet Fragment". The error message mentioned above is displayed when you try to loot it.

If I had to guess there is a limit on how many of these items the player can posses at once, and since they only need four for the quest, the spawned object giving you a stack of six breaks something. 

**How it should work:**
Wowhead Description: https://www.wowhead.com/quest=14268/deep-impact

Youtube Playthrough: https://www.youtube.com/watch?v=nwLy7H6qZDA

**Database links:**

**Comment by Frapp3** [comment]
Please fix this! I want to complete the loremaster achievement
