### ISSUE TITLE
Book of Glyph Mastery

### ISSUE THREAD

**Issue by JadedNate** [gamefreedomgit/Deathwing#6]
**Description:**
The droprate on Book of Glyph Mastery seems to be rarer than intended. I remember on retail at least getting 2-3 a day while farming. Alas, I did not get any at all from the past several times I've tried to farm them since release of this server. :(

**How to reproduce:**
Attempt to farm Northrend mobs for Book of Glyph Mastery.

**How it should work:**
I don't know the appropriate drop chances, but especially since the realm is supposed to be sped up an insane amount anyway I'd at least double or even triple the chances.

**Database links:**
https://www.wowhead.com/cata/item=45912/book-of-glyph-mastery
(https://cata-twinhead.twinstar.cz/?item=45912)

**Comment by GM-Nightmaree** [comment]
Where are you farming it?
drop rate is low 
aka max 14% it should take some time to farm

**Comment by UltraNix** [comment]
Fixed.

**Comment by nirajbajracharya61** [comment]
> Where are you farming it? drop rate is low aka max 14% it should take some time to farm

Where should we be farming? :)

**Comment by NirajBajracharya** [comment]
> Where are you farming it? drop rate is low aka max 14% it should take some time to farm

Where should we be farming? :)
