### ISSUE TITLE
Drakefist Hammer Recipe

### ISSUE THREAD

**Issue by jeremicio** [gamefreedomgit/Deathwing#65]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
I tryied to learn this recipe on my rogue but it doesn't shows up on any bm trainer. I learned this one on my bf warrior but i can't with this other character.

**Comment by PanJanuszek** [comment]
fixed 05.05.2024, server restart required
