### ISSUE TITLE
 zul'gurub dungeon

### ISSUE THREAD

**Issue by Humberto95159** [gamefreedomgit/Deathwing#66]
![bug mazmorra](https://github.com/gamefreedomgit/Deathwing/assets/167715612/111360e3-f033-4218-b1ce-244e8c700d62)
 
how do I get a stuck character

https://www.wowhead.com/es/zone=1977/zulgurub

It can't load and the error appears as I send it to the home stone somewhere from the page

**Comment by Waroxx-QA** [comment]
Install a new client and put it on a different folder ( without deleting the old one ). Log and try to tag on it. if you get the same error then it's a hardware issue.
