### ISSUE TITLE
Witchwing harpies are unreachable in the Northern Barrens

### ISSUE THREAD

**Issue by LuckyLuc96** [gamefreedomgit/Deathwing#68]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The two harpies I found were unreachable, even when up close. I believe their model might not reflect where they actually are, and that they are either under the ground or very high up.

**How to reproduce:**
1) Be in melee range of this enemy
2) Try to attack the enemy
3) Be out of range

**How it should work:**
Melee should work against this enemy.

**Database links:**
https://www.wowhead.com/classic/npc=3276/witchwing-harpy

![Screenshot from 2024-05-04 14-55-39](https://github.com/gamefreedomgit/Deathwing/assets/94196417/69471a26-4d80-40e6-8c7a-7fe85b7c7388)

**Comment by PanJanuszek** [comment]
fixed 05.05.2024 after restart
