### ISSUE TITLE
[Quest] Northern Barrens: Crossroads Caravan Pickup

### ISSUE THREAD

**Issue by Tiebob99** [gamefreedomgit/Deathwing#69]
**Description:**
The Kodo I have to protect during this quest takes way too much damage and dies too quickly to complete the quest normally. The mobs also sometimes take multiple shots to kill. I can get about 2/3 of the way to Grol'dom Farm before the kodo dies and I fail the quest.

**How to reproduce:**
Accept the quest and talk to Halga Bloodeye to summon a kodo to mount. right click to ride the kodo and use the hotbar provided by the vehicle to target and kill quilboar on the way to Grol'dom Farm. The kodo dies before reaching the farm and the quest fails.

**How it should work:**
The Quilboar should deal much less damage to the kodo
Here is a video I found on youtube from 12 years ago for reference: 
https://www.youtube.com/watch?v=46CgGXWUzQs

**Database links:**
https://www.wowhead.com/cata/quest=13949/crossroads-caravan-pickup

**Comment by PanJanuszek** [comment]
fixed 05.05.2024 after restart
