### ISSUE TITLE
Quest Just You and Mathias

### ISSUE THREAD

**Issue by Xykyta1** [gamefreedomgit/Deathwing#71]
[//]: # Quest Just You and Mathias
[//]: # https://www.wowhead.com/cata/quest=27636/just-you-and-mathias

Master Mathias Shaw does not appear under tower - cant end quest.
![nomats](https://github.com/gamefreedomgit/Deathwing/assets/159961699/868dc16f-52d8-4fd4-a97e-6b142ad41a0c)

And I canceled the quest and now I can't take it again. Story line is stuck

**Comment by Xykyta1** [comment]
found him today

**Comment by PanJanuszek** [comment]
fixed 08.05.2024, after restart
