### ISSUE TITLE
Blood Elf Eviscerate 

### ISSUE THREAD

**Issue by Netrinil** [gamefreedomgit/Deathwing#75]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest is supposed to be turned in at Pathstalker Kariel but is instead directed to Well Watcher Solanian.

**How to reproduce:**
1. Create a Blood Elf rogue.
2. Complete the Rogue Training quest from Magistrix Elona.
3. Accept the Evisceration quest from Pathstalker Kariel.
4. Successfully use Eviscerate 3 times.
5. Follow quest turn in details, only to find it's turned in to the person standing above him.

**How it should work:**
Quest is supposed to be turned in at Pathstalker Kariel.

**Database links:**
[https://wowpedia.fandom.com/wiki/Evisceration](url) (This quest and Pathstalker Kariel have been modified/removed in retail so I couldn't find a wowhead link)

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/c439d896-c34c-44e1-a540-f8172cc8d62b)

works as should since 2.0.3

**Comment by Netrinil** [comment]
Then would it be possible to update this quest text?
![WoWScrnShot_051024_100040](https://github.com/gamefreedomgit/Deathwing/assets/78034181/fee356b6-b3f3-4d4f-9776-7d48860759d2)
