### ISSUE TITLE
Quest "a-lost-companion" can't be completed.

### ISSUE THREAD

**Issue by wuyazhishen-coder** [gamefreedomgit/Deathwing#77]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Quest "a-lost-companion" can't be completed.
https://www.wowhead.com/quest=13564/a-lost-companion
**How to reproduce:**

**How it should work:**

**Database links:**

**Comment by PanJanuszek** [comment]
fixed 23.05.2024, after restart
