### ISSUE TITLE
Ace in the Hole Quest Bug

### ISSUE THREAD

**Issue by TristanTheart** [gamefreedomgit/Deathwing#81]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The first 2 steps of the quest (Ace in the Hole - Western Plaguelands) work as intended. The third step is not working ; upon reaching the location the quest progress does not update so we are unable to complete the quest.

**How to reproduce:**
Do the first 2 steps of the Ace in the Hole quest
**How it should work:**
https://www.youtube.com/watch?v=BmGs9IqZAiU
The quest is supposed to auto-complete upon reaching the NPC Lurid.

**Database links:**
https://www.wowhead.com/quest=27089/ace-in-the-hole

**Comment by PanJanuszek** [comment]
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/77cfad26-6f90-4c89-b570-6d55814f729a)
you are wrong, not Lutrid, there are skeletons remains on road, that's the trigger
