### ISSUE TITLE
Quest "Recover the Cargo!"

### ISSUE THREAD

**Issue by skarabeus121** [gamefreedomgit/Deathwing#85]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
When i accept the Quest i will get in inventory the "Renn´s Supplies" It would included 2 stuffs (Diving gear and salvage supplies" but its empty.

**Comment by PanJanuszek** [comment]
cannot reproduce 
![image](https://github.com/gamefreedomgit/Deathwing/assets/398043/151fb784-0e50-41d1-a689-36538b7b07bc)
