### ISSUE TITLE
"The Durnholde Challenge: D-1000" quest bug

### ISSUE THREAD

**Issue by Netrinil** [gamefreedomgit/Deathwing#88]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
D-1000 quest trigger is bugged. Quest is still acceptable from Captain Jekyll.

**How to reproduce:**
Be on the quest The Durnholde Challenge: Infernus.
Kill Infernus.

**How it should work:**
Killing Infernus while on The Durnholde Challenge: Infernus should automatically give you this quest.

**Database links:**
[The Durnholde Challenge: D-1000](https://www.wowhead.com/quest=28647/the-durnholde-challenge-d-1000)
[The Durnholde Challenge: Infernus](https://www.wowhead.com/quest=28646/the-durnholde-challenge-infernus)

**Comment by PanJanuszek** [comment]
fixed 23.05.2024, after restart
