### ISSUE TITLE
(Quest) The Heart of Mokk is empty/broken

### ISSUE THREAD

**Issue by mafiaknight** [gamefreedomgit/Deathwing#9]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
You can accept the The Heart of Mokk quest from Unbagwa without having done Stranglethorn Fever beforehand. When you do, it has no text in the quest description and does not give any rewards for completion (including xp). On completion, it just cycles through part one again. (is a repeatable quest) (have not tested if it works properly when continuing from the quest chain)

**How to reproduce:**
accept the quest from Witch Doctor Unbagwa in Spirit Den/The Cape of Stranglethorn without having done Stranglethorn Fever beforehand. May be "broken" _because_ I did not do the first quest, but then it should not be offered.

**How it should work:**
https://www.wowhead.com/quest=26598/the-heart-of-mokk

**Database links:**
![WoWScrnShot_041324_180130](https://github.com/gamefreedomgit/Deathwing/assets/89418074/eca2bb80-df37-4719-a1d0-5b66e5d25421)
![WoWScrnShot_041324_180140](https://github.com/gamefreedomgit/Deathwing/assets/89418074/91407305-ffd4-4464-8c76-f3ba3ffe0d95)
![WoWScrnShot_041324_181027](https://github.com/gamefreedomgit/Deathwing/assets/89418074/525aa800-229f-4dcf-a534-29b8d569105f)

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/2722
