### ISSUE TITLE
quest bugs at Nothern Barrens

### ISSUE THREAD

**Issue by XeersLee** [gamefreedomgit/Deathwing#97]
**Description:**
quest bugs at Nothern Barrens
1. counterattack!: there's no creeps after i take this quest and talk to npc. so i can't got the item for this quest
2. Mor'shan caraven delivery: kodo doesn't move after i talk to npc and mount it.

**How to reproduce:**
normal step, finish quest one by one

**How it should work:**
it can be finished

**Database links:**
https://www.wowhead.com/quest=29111/morshan-caravan-delivery
https://www.wowhead.com/quest=4021/counterattack

**Comment by PanJanuszek** [comment]
Fixed 23.05.2024, after restart
